#pragma once

//
// This file contains all IDs of game assets 
//
//NOTE !!!!!!!
//NAMING CONVENTION: Not accounting for old name given by prof, most sprite for the right direction will be an even number, usually 0 or 1 . EX: 13400 for walking right, 13410 for walking left. second sprite for walking right could be 
// 13401, 13402, and so on. 
// In case where there is little space left, say , walking is ~600, running is ~ 700, but you need walking while grabbing. So if walking is 600, 601,602,
// 610,611,612, then the walking grab could be 620, 621, 622, 630, 631 , 632

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_VERTICAL_OBJECT 6 //Mostly repeatable item that is similiar to plaform, but vertical !!! BLOCKABLE!!

#define OBJECT_TYPE_BACKGROUND_ITEM 7
#define OBJECT_TYPE_LOOT_BRICK 8 //Breakable/interactable brick that can drop item
#define OBJECT_TYPE_BIG_COLOR_BRICK 9 //Brick that you can only jump on top, no collision otherwise
#define OBJECT_TYPE_TUNNEL 10
#define OBJECT_TYPE_SHOOTING_PLANT 11 //Chomper
#define OBJECT_TYPE_TURTLE 12
#define OBJECT_TYPE_EATING_PLANT 13 // Chomper, does not shoot.
#define OBJECT_TYPE_FLYING_GOOMBA 14 //Goomba that can fly
#define OBJECT_TYPE_FLYING_TURTLE 15 //Turtle that can fly
#define OBJECT_TYPE_GROUND_BUTTON 16 //Button that can be pressed by mario to activate something
#define OBJECT_TYPE_LEAF 17
#define OBJECT_TYPE_MUSHROOM 18


#define OBJECT_TYPE_PORTAL	50
//Projectile (>500)
#define OBJECT_TYPE_PLANT_PROJECTILE 500 //Plant fireballs
#define OBJECT_TYPE_MARIO_TAIL_ATTACK 501
//System obj definition
#define OBJECT_TYPE_DETECTION_ZONE 1000


#define OBJECT_TYPE_PARTICLE 1100
//Secret 10000>
#define OBJECT_TYPE_SECRET_BRICK_WORLD_1_1 10001 //Brick that has a button that turn brick around it into coin

//System
#define OBJECT_TYPE_SYSTEM 99999 // Anything that is not visible, but is used to control the game. EX: Camera, HUD, etc...

#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 


#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)

#define ID_SPRITE_GROUND 60000
#define ID_SPRITE_GROUND_BEGIN (ID_SPRITE_GROUND + 1000)
#define ID_SPRITE_GROUND_MIDDLE (ID_SPRITE_GROUND + 2000)
#define ID_SPRITE_GROUND_RIGHT (ID_SPRITE_GROUND + 3000)
//Second layer of ground

#define ID_SPRITE_GROUND_2_BEGIN (ID_SPRITE_GROUND+ 4000)
#define ID_SPRITE_GROUND_2_MIDDLE (ID_SPRITE_GROUND + 5000)
#define ID_SPRITE_GROUND_2_RIGHT (ID_SPRITE_GROUND + 6000)

#define ID_SPRITE_PLAFORM_WOODEN (ID_SPRITE_GROUND + 7000)
//Background items
// 7 - item - 0 - bottom/top(1/0) - left/right(1/0)
//Bushes 1 = 0;                     
#define ID_SPRITE_BUSH_TOP_LEFT 70001
#define ID_SPRITE_BUSH_TOP_RIGHT 70000
#define ID_SPRITE_BUSH_BOTTOM_LEFT 70011
#define ID_SPRITE_BUSH_BOTTOM_RIGHT 70010
#define ID_SPRITE_BUSH_ADDITIONAL_1 70100

// Cloud stuffs
// in database
// LOOOTS
// mushroom stuffs.
#define ID_SPRITE_MUSHROOM 80000



//Some brick stuffs here (color, big brick) - 90000~
#define ID_SPRITE_BRICK_COLOR_START 90000


//Tunnel start
#define ID_SPRITE_TUNNEL_START 100000

#define ID_SPRITE_PLANT_LOOK_UP_RIGHT 101000
#define ID_SPRITE_PLANT_LOOK_DOWN_RIGHT 101001
#define ID_SPRITE_PLANT_LOOK_UP_LEFT 101010
#define ID_SPRITE_PLANT_LOOK_DOWN_LEFT 101011
#define ID_SPRITE_PLANT_STRAIGHT_UP 101100
#define ID_SPRITE_PLANT_BULLET  101200

#define ID_ANI_PLANT_STRAIGHT_UP 1010

//Invinsible block

//Leaf
#define ID_SPRITE_LEAF_RIGHT 110000
#define ID_SPRITE_LEAF_LEFT 110001


//Turtle stuff ~ 120000


//Ground button
#define ID_SPRITE_GROUND_BUTTON 130000


//End game zone stuffs
#define ID_SPRITE_END_ZONE_START_SPIKE 600000


//Particle stuffs/ Effects
#define ID_SPRITE_PARTICLE_BRICK 900000



#define ID_SPRITE_INVISIBLE_BLOCK 999999

